version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - data-volume:/data/redis

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
